### ISSUE TITLE
Tests on Python 2 are broken

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.app.session#2]
See https://travis-ci.org/zopefoundation/zope.app.session/builds/443425283

**Comment by jamadden** [comment]
This is due to ZODB 5.3 and above using newer pickle protocols. The test is trying to pickle an open file and expecting it to fail, but the change notes for 5.3.0 specifically call that out:

> Note
> On Python 2, this will now allow open file objects (but not open blobs or sockets) to be pickled (loading the object will result in a closed file); previously this would result in a TypeError. Doing so is not recommended as they cannot be loaded in Python 3.
